// Console copy. House rule: no em-dashes.
export const A = {
  brand: 'POLITIFACE // CONSOLE',
  notAvailable: 'The console is not available for this account.',
  live: (n: number) => `LIVE ${n}`,
  searchPlaceholder: 'Search people, classes, sessions, codes',
  searchHint: 'Cmd-K',
  noHits: 'No matches.',
  nav: { home: 'Home', search: 'Search', invites: 'Invites', audit: 'Audit', rail: 'Console' },
  titles: {
    home: 'Overview',
    search: 'Search',
    person: 'Person',
    klass: 'Class',
    session: 'Session',
    invites: 'Invites',
    audit: 'Audit log',
  },
  comingIn2b: 'Coming in 2b',
  loading: 'Loading',
  lobby: 'Lobby',

  panes: {
    left: 'Linked records',
    center: 'Timeline',
    right: 'Properties and actions',
  },

  timeline: {
    header: 'Timeline, newest first',
    empty: 'Nothing recorded yet.',
    unverifiedEmail: '(typed email, unverified)',
  },

  home: {
    statPeople: 'People',
    statStudents: 'Students enrolled',
    statAnsweredLive7d: 'Answered live (7d)',
    statPendingRequests: 'Pending requests',
    statSystem: 'System',
    healthNominal: 'NOMINAL',
    healthCheck: 'CHECK',
    healthUnknown: 'UNKNOWN',
    liveNow: 'Live now',
    noLiveSessions: 'No live sessions.',
    inRoom: 'in room',
    startedAt: 'started',
    onboardingFunnel: 'Onboarding funnel',
    colClass: 'Class',
    colMembers: 'Members',
    colStudents: 'Students',
    colAnsweredLive: 'Answered live',
    colPracticed7d: 'Practiced 7d',
    needsAttention: 'Needs attention',
    allClear: 'All clear.',
    activity: 'Activity',
  },

  person: {
    kind: 'Person',
    classes: 'Classes',
    liveSessions: 'Live sessions',
    devices: 'Devices',
    pushDevices: 'push devices',
    properties: 'Properties',
    created: 'created',
    lastSignIn: 'last sign-in',
    school: 'school',
    none: 'none',
    iosApp: 'iOS app',
    web: 'web',
    notSeen: 'not seen',
    practice30d: 'practice 30d',
    actions: 'Actions',
    grant: 'Grant instructor access',
    revoke: 'Revoke instructor access',
    confirmGrant: 'Grant',
    confirmRevoke: 'Revoke',
    confirmSuffix: 'instructor access for',
    confirmGroupLabel: 'Confirm instructor access change',
    confirm: 'Confirm',
    cancel: 'Cancel',
    badgeAdmin: 'ADMIN',
    badgeInstructor: 'INSTRUCTOR',
    badgeStudent: 'STUDENT',
    disabledActions: ['Move class', 'Sign out everywhere', 'Rename', 'Delete account'],
    never: 'never',
    unknown: 'unknown',
  },

  klass: {
    membersLabel: 'Members',
    sessionsLabel: 'Sessions',
    properties: 'Properties',
    joinCode: 'join code',
    reporting: 'reporting',
    reportingDefault: 'default',
    created: 'created',
    funnel: 'Funnel',
    members: 'members',
    students: 'students',
    answeredLive: 'answered live',
    practiced7d: 'practiced 7d',
    owner: 'owner',
    unknown: 'unknown',
    joined: 'joined',
  },

  session: {
    participants: 'Participants',
    properties: 'Properties',
    professor: 'professor',
    unknown: 'unknown',
    code: 'code',
    perQuestion: 's per question',
    guests: 'guests',
    guestsAllowed: 'allowed',
    guestsOff: 'off',
    questions: 'Questions',
    answered: 'answered',
    correct: 'correct',
    guestSuffix: '(guest)',
    naCorrectRate: 'n/a',
  },

  invites: {
    emailLabel: 'Their email (optional)',
    noteLabel: 'Note (optional)',
    create: 'Create invite link',
    linkLabel: 'Invite link',
    copy: 'Copy',
    copied: 'Copied',
    colCode: 'Code',
    colStatus: 'Status',
    colFor: 'For',
    colBy: 'By',
    colExpires: 'Expires',
    colActions: 'Actions',
    revoke: 'Revoke',
    confirmPrompt: (code: string) => `Revoke invite ${code}?`,
    confirmGroupLabel: 'Confirm invite revocation',
    confirm: 'Confirm',
    cancel: 'Cancel',
  },

  audit: {
    colWhen: 'When',
    colWho: 'Who',
    colAction: 'Action',
    colTarget: 'Target',
    colDetails: 'Details',
    unknownActor: 'unknown',
    noTarget: 'console',
    fallbackPerson: 'person',
    fallbackClass: 'class',
    fallbackSession: 'session',
    filterLabel: 'Action',
    filterAll: 'All actions',
    actorFilterLabel: 'Actor',
    actorFilterAll: 'All actors',
  },
}

// The admin-writable action kinds app.audit() records, for the audit
// log's filter. Kept in sync with supabase/migrations/20261004000200_admin_console.sql.
export const AUDIT_ACTIONS = [
  'console_open',
  'view_person',
  'faculty_granted',
  'faculty_revoked',
  'invite_minted',
  'invite_revoked',
] as const
