// lib/core/audio/sound_service.dart
//
// Five short synthesized UI sounds layered on top of the existing haptics.
// Sounds are original works generated by scripts/generate_sounds.py and
// committed under app/assets/audio/. Playback is fire-and-forget and every
// failure path degrades to silence: sound is never load-bearing feedback
// (color + icon + haptic + semantics announcements carry the information).

import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../app/providers.dart';
import '../../features/settings/data/settings_service.dart';

/// The app's five sound effects. One asset per effect, all in the same
/// woody / paper palette and the same key so sequences stay musical.
enum SoundEffect {
  /// Card flip to reveal the answer (paper turn).
  flip('flip.wav'),

  /// Correct answer reveal (single woodblock tick).
  correct('correct.wav'),

  /// Incorrect answer reveal (muted felt thud, neutral not punitive).
  incorrect('incorrect.wav'),

  /// Day complete / session summary (two-note woody resolve).
  complete('complete.wav'),

  /// Mock FCLE pass (ascending arpeggio).
  milestone('milestone.wav');

  const SoundEffect(this.file);
  final String file;

  /// Asset path relative to the audioplayers asset prefix (`assets/`).
  String get assetPath => 'audio/$file';
}

/// Preloads the five effects into [AudioPool]s and plays them with a
/// synchronous, no-throw, fire-and-forget [play].
///
/// The iOS audio session is `ambient`: sounds respect the ringer switch and
/// mix under (never interrupt) whatever the student is already listening to.
/// If [init] fails for any reason (missing plugin in widget tests, asset
/// load failure, session error), every [play] is a silent no-op.
class SoundService {
  /// Cached preference so [play] never awaits the database. Pushed by
  /// [SoundEnabledNotifier]; default ON matches the unset preference.
  bool enabled = true;

  bool _initStarted = false;
  final Map<SoundEffect, AudioPool> _pools = {};

  /// Warm up the audio session and preload every effect so the first real
  /// play has no load hit. Safe to call more than once; only the first call
  /// does work. Never throws.
  Future<void> init() async {
    if (_initStarted) return;
    _initStarted = true;
    try {
      // `ambient` respects the ringer switch and mixes with other audio by
      // AVFoundation semantics. audioplayers 6.4 asserts if mixWithOthers is
      // also passed explicitly with ambient, so options stay empty here.
      // (Android config is future-proofing; the app is iOS-only today.)
      await AudioPlayer.global.setAudioContext(
        AudioContext(
          iOS: AudioContextIOS(
            category: AVAudioSessionCategory.ambient,
          ),
          android: const AudioContextAndroid(
            contentType: AndroidContentType.sonification,
            usageType: AndroidUsageType.assistanceSonification,
            audioFocus: AndroidAudioFocus.none,
          ),
        ),
      );
      for (final effect in SoundEffect.values) {
        _pools[effect] = await AudioPool.createFromAsset(
          path: effect.assetPath,
          maxPlayers:
              (effect == SoundEffect.correct || effect == SoundEffect.incorrect)
                  ? 2
                  : 1,
        );
      }
    } on Object catch (e) {
      // No plugin (widget tests), asset missing, or session failure:
      // degrade to a silent no-op. Sound is never load-bearing.
      debugPrint('[sound] init failed, sounds disabled: $e');
      _pools.clear();
    }
  }

  /// Fire-and-forget playback. Synchronous, never throws, never awaited in
  /// a UI path. No-op when the toggle is off or [init] did not complete.
  void play(SoundEffect effect) {
    if (!enabled) return;
    final pool = _pools[effect];
    if (pool == null) return;
    unawaited(
      pool.start().then<void>((_) {}).catchError((Object e) {
        debugPrint('[sound] play(${effect.name}) failed: $e');
      }),
    );
  }
}

final soundServiceProvider = Provider<SoundService>((ref) => SoundService());

/// Whether sound effects are enabled. Default ON; persisted via
/// [SettingsService] in app_meta. Modeled on [ThemeModeNotifier]: async
/// load in the constructor, [set] persists and pushes the cached bool into
/// [SoundService] so playback never touches the database.
final soundEnabledProvider = StateNotifierProvider<SoundEnabledNotifier, bool>(
  (ref) => SoundEnabledNotifier(
    SettingsService(ref.read(databaseProvider)),
    ref.read(soundServiceProvider),
  ),
);

class SoundEnabledNotifier extends StateNotifier<bool> {
  SoundEnabledNotifier(this._settings, this._sound) : super(true) {
    _load();
  }

  final SettingsService _settings;
  final SoundService _sound;

  /// True once the user has toggled explicitly; the async initial load must
  /// never clobber a choice made while it was still in flight.
  bool _userSet = false;

  Future<void> _load() async {
    final enabled = await _settings.soundEffectsEnabled();
    if (_userSet || !mounted) return;
    _sound.enabled = enabled;
    state = enabled;
  }

  Future<void> set(bool value) async {
    _userSet = true;
    state = value;
    _sound.enabled = value;
    await _settings.setSoundEffectsEnabled(value);
  }
}
